### ISSUE TITLE
Right mouse click on "Paste" ends with an error

### ISSUE THREAD

**Issue by Goster** [princejwesley/Mancy#104]
1. copy following code:
```javascript
var webdriver = require('selenium-webdriver'),
    By = require('selenium-webdriver').By,
    until = require('selenium-webdriver').until,
    chrome = require('selenium-webdriver/chrome');

var options = new chrome.Options();
options.setChromeBinaryPath("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe");    

var driver = new webdriver.Builder()
    .forBrowser('chrome')
    .setChromeOptions(options)
    .build();

driver.get('http://www.google.com/ncr');
driver.findElement(By.name('q')).sendKeys('webdriver');
driver.findElement(By.name('btnG')).click();
driver.wait(until.titleIs('webdriver - Google Search'), 1000);
driver.quit();
```
2. open new instance of Mancy
3. right click on the row with text input field and choose option "Paste"
4. it gives us an error in console:

Error: Could not call remote function ``. Check that the function signature is correct. Underlying error: Menu.sendActionToFirstResponder is not a function
Error: Could not call remote function ``. Check that the function signature is correct. Underlying error: Menu.sendActionToFirstResponder is not a function
    at callFunction (D:\Programy\Mancy\resources\atom.asar\browser\lib\rpc-server.js:238:11)
    at EventEmitter.<anonymous> (D:\Programy\Mancy\resources\atom.asar\browser\lib\rpc-server.js:319:12)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (D:\Programy\Mancy\resources\atom.asar\browser\api\lib\web-contents.js:133:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
  at metaToValue (D:\Programy\Mancy\resources\atom.asar\renderer\api\lib\remote.js:168:13)
  at Menu.remoteMemberFunction [as popup] (D:\Programy\Mancy\resources\atom.asar\renderer\api\lib\remote.js:110:18)
  at Repl.onContextMenu (D:\Programy\Mancy\resources\app\components\Repl.js:473:17)

**Comment by princejwesley** [comment]
@Goster this could be electron bug. I'll look into that and update here

**Comment by princejwesley** [comment]
@Goster can you please confirm the fix?

**Comment by Goster** [comment]
yes I confirm that it is fixed in new build. thx
