### ISSUE TITLE
Fatal crash on startup OSX El Capitan 3.0 AND 2.2.2

### ISSUE THREAD

**Issue by mattsfrey** [princejwesley/Mancy#123]
Get this in the electron exception window as soon as I try to run the app via double click on the .app file.

```
Uncaught Exception:
TypeError: Cannot set property '__proto__' of null
    at Object.<anonymous> (/Applications/Mancy.app/Contents/Resources/atom.asar/browser/api/screen.js:4:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at onReady (/Applications/Mancy.app/Contents/Resources/app/main/index.js:334:31)
    at EventEmitter.<anonymous> (/Applications/Mancy.app/Contents/Resources/app/main/index.js:282:5)
    at emitTwo (events.js:92:20)
```

**Comment by princejwesley** [comment]
I suspect electron's `screen` object is null.

**Comment by princejwesley** [comment]
@mattsfrey  Are you getting any one of the below error message before getting `Cannot set property '__proto__' of null`?
> "Cannot initialize \"screen\" module before app is ready" 

or

> "Failed to get screen information"

**Comment by mattsfrey** [comment]
I was not, first error msg is what I posted. Note: I have since pulled the source and done npm install etc., and now when I double click the app it opens as it should, so it could be an environment factor.
