### ISSUE TITLE
new Promise(() => {}) fails with "Cannot read property 's' of undefined"

### ISSUE THREAD

**Issue by jakubholynet** [princejwesley/Mancy#132]
Mancy looks awesome but I have some problems with it, including this: When executing `new Promise(() => {})`, it fails with
> Cannot read property 's' of undefined

Stack trace: 

```
at Object.object (/Users/me/.nvm/versions/node/v6.2.1/lib/node_modules/mancy/dist/Mancy-darwin-x64/Mancy.app/Contents/Resources/app/common/ReplOutput.js:311:25)
 at Object.transformObject (/Users/me/.nvm/versions/node/v6.2.1/lib/node_modules/mancy/dist/Mancy-darwin-x64/Mancy.app/Contents/Resources/app/common/ReplOutput.js:829:105)
 at Some.highlight (/Users/me/.nvm/versions/node/v6.2.1/lib/node_modules/mancy/dist/Mancy-darwin-x64/Mancy.app/Contents/Resources/app/common/ReplOutput.js:789:37)
 at transpileCallback (/Users/me/.nvm/versions/node/v6.2.1/lib/node_modules/mancy/dist/Mancy-darwin-x64/Mancy.app/Contents/Resources/app/components/ReplActiveInput.js:661:143)
 at Object.runInContext (/Users/me/.nvm/versions/node/v6.2.1/lib/node_modules/mancy/dist/Mancy-darwin-x64/Mancy.app/Contents/Resources/app/common/ReplCommon.js:427:7)
 at ReplActiveInput.transpileAndExecute (/Users/me/.nvm/versions/node/v6.2.1/lib/node_modules/mancy/dist/Mancy-darwin-x64/Mancy.app/Contents/Resources/app/components/ReplActiveInput.js:678:32)
 at /Users/me/.nvm/versions/node/v6.2.1/lib/node_modules/mancy/dist/Mancy-darwin-x64/Mancy.app/Contents/Resources/app/components/ReplActiveInput.js:843:20
```

Environment:
- OS X 10.10.5
- Node 6.2.1
- Mancy 3.0.0
- Using strict JS, no babel transf.

Thank you!

**Comment by jakubholynet** [comment]
It happens at these lines: 

```js
        var obj = o[Object.getOwnPropertyNames(o)[0]];
        var status = obj.s === 0 ? 'pending' : obj.s === 1 ? 'resolved' : 'rejected'; // <---- here
```
The thing is that even though `o instanceof BabelCoreJS.default.Promise` is true, `Object.getOwnPropertyNames(o)` (as well as `Object.keys(o)`) returns an empty array.

**Comment by princejwesley** [comment]
@jakubholynet Yes. Looking into it! 😄

**Comment by jakubholynet** [comment]
On the other hand, `makeMirror(o)` has the functions "status,promiseValue,className,constructoeHandle_,allocateTransientHandle_,handle"

I guess that we believe that this is `BabelCoreJS.default.Promise` but it is (at the same time) the native node Promise and thus should not be treated as a `BabelCoreJS.default.Promise`.

**Comment by princejwesley** [comment]
@jakubholynet Yes, I fixed it! Having style issue. I'll merge it shortly!

**Comment by princejwesley** [comment]
![image](https://cloud.githubusercontent.com/assets/1622515/15970876/91d8a0ca-2f54-11e6-92c7-b6ecc97e304a.png)

**Comment by jakubholynet** [comment]
I assume the fix might break the code when using an older Node that does not have native promises, but I guess we do not want to support that anyway :)

**Comment by princejwesley** [comment]
@jakubholynet Electron is bundled with node, therefore, no issues

**Comment by princejwesley** [comment]
@jakubholynet Thanks 👍

**Comment by jakubholynet** [comment]
Thank you for the quick fix!
