### ISSUE TITLE
app.isUnityRunning is not a function

### ISSUE THREAD

**Issue by agauniyal** [princejwesley/Mancy#139]
```
TypeError: app.isUnityRunning is not a function
    at EventEmitter.<anonymous> (/usr/share/mancy/main/index.js:176:76)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at BrowserWindow.on (/usr/share/electron/resources/electron.asar/browser/api/browser-window.js:72:9)
    at emitOne (events.js:101:20)
    at BrowserWindow.emit (events.js:188:7)
```

Arch linux x64, node v6, installed via aur

**Comment by princejwesley** [comment]
@ayanonagon can you please upgrade electron version by running `npm update`.

**Comment by agauniyal** [comment]
I'll report once electron package is updated on aur. It's already marked as out of date.

**Comment by agauniyal** [comment]
solved.
