### ISSUE TITLE
Installing some packages will fail in Mancy

### ISSUE THREAD

**Issue by bmamouri** [princejwesley/Mancy#160]
I am trying to install `marky-markdown` package, but the installation failed with the following error:

var marky = require("marky-markdown")

##### Message
Cannot read property 'id' of null
##### Stack Trace
```js
TypeError: Cannot read property 'id' of null
    at EventEmitter.<anonymous> (/Applications/Mancy.app/Contents/Resources/app/main/index.js:208:33)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.<anonymous> (/Applications/Mancy.app/Contents/Resources/electron.asar/browser/api/web-contents.js:156:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

#### System Details
 | …
------------ | -------------
**Platform** | darwin
**Arch** | x64
**Electron Version** | 1.2.6
**Mancy Version** | 3.1.0

**Comment by MutableLoss** [comment]
I was just having this issue with node-fetch today. 

My error existed because I was trying to load from my npm prefix path ( ~ /.npm). In that path Mancy was try to load the node-fetch folder where it had directories of the installed versions, but it did not have the module itself. 

Once I loaded the correct module path (~ /.npm/lib/node_modules) which had the actual node-fetch module, it loaded without a hitch, and I did not see another error about the missing _prop id_.
