### ISSUE TITLE
Application Error when require lib

### ISSUE THREAD

**Issue by adw0rd** [princejwesley/Mancy#176]
Run:
> const t = require('jsdoctap')

##### Message
Cannot read property 'id' of null
##### Stack Trace
```js
TypeError: Cannot read property 'id' of null
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/mancy/dist/Mancy-darwin-x64/Mancy.app/Contents/Resources/app/main/index.js:208:33)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/mancy/dist/Mancy-darwin-x64/Mancy.app/Contents/Resources/electron.asar/browser/api/web-contents.js:156:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

#### System Details
 | …
------------ | -------------
**Platform** | darwin
**Arch** | x64
**Electron Version** | 1.2.6
**Mancy Version** | 3.1.0

**Comment by adw0rd** [comment]
When run "mancy" on zsh:

[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0





---

16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
