### ISSUE TITLE
Collapsable error output 

### ISSUE THREAD

**Issue by pmros** [princejwesley/Mancy#25]
It think error outp should be collapsed by default.

Example (wrong) input:
```javascript
1+++
```
Now you get this output: 
```
ReferenceError:  Invalid left-hand side expression in postfix operation
  at exports.createScript (vm.js:24:10)
  at REPLServer.defaultEval (repl.js:137:25)
  at bound (domain.js:250:14)
  at REPLServer.runBound [as eval] (domain.js:263:12)
  at REPLServer.<anonymous> (repl.js:393:12)
  at emitOne (events.js:77:13)
  at REPLServer.emit (events.js:169:7)
  at REPLServer.Interface._onLine (readline.js:210:10)
```
It would be nicer this way: 
```
> ReferenceError:  Invalid left-hand side expression in postfix operation
```
click on ( >)  to view error details

**Comment by princejwesley** [comment]
Fixed in v2.

**Comment by princejwesley** [comment]
Merged to master
