### ISSUE TITLE
Some problem with npm install

### ISSUE THREAD

**Issue by xgrommx** [princejwesley/Mancy#58]
Hi @princejwesley When I try install npm dependencies I got this error:

```
npm ERR! Cloning into bare repository 'C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-princejwesley-font-manager-git-3684d2cffffd1f08ab15a7fa0f01449f'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

**Comment by pmros** [comment]
Same problem here. Use https protocol instead git protocol. Change package.json:
```
"font-manager": "https://github.com/princejwesley/font-manager.git"
```

**Comment by princejwesley** [comment]
@pmros @xgrommx https works ?

**Comment by pmros** [comment]
yes

**Comment by princejwesley** [comment]
Thanks.

**Comment by xgrommx** [comment]
@princejwesley Very strange because earlier I could build Mancy for windows x64.

**Comment by xgrommx** [comment]
This is full the stack trace:
```
gyp ERR! clean error
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\tmp\Mancy\node_modules\nslog\build\Release\nslog.node'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\tmp\\Mancy\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\tmp\Mancy\node_modules\nslog
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\tmp\\Mancy\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--runtime=electron" "--target=0.34.3" "--arch=x64"
npm ERR! node v5.0.0
npm ERR! npm  v2.14.11
npm ERR! code ELIFECYCLE
npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\tmp\Mancy\node_modules\npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (C:\tmp\Mancy\node_modules\electron-rebuild\lib\spawn.js:55:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

npm WARN ENOENT ENOENT: no such file or directory, open 'C:\tmp\Mancy\node_modules\npm-debug.log\package.json'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! mancy@2.0.1 postinstall: `electron-rebuild`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the mancy@2.0.1 postinstall script 'electron-rebuild'.
npm ERR! This is most likely a problem with the mancy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mancy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\tmp\Mancy\npm-debug.log
```

**Comment by princejwesley** [comment]
@xgrommx thanks. I'll look into that

**Comment by princejwesley** [comment]
One of the below suggestions might help
1) [permission-error](https://github.com/npm/npm/wiki/Troubleshooting#permission-error)
2) [try-clearing-the-npm-cache](https://github.com/npm/npm/wiki/Troubleshooting#try-clearing-the-npm-cache)

**Comment by princejwesley** [comment]
@xgrommx Follow [node-gyp](https://github.com/nodejs/node-gyp#installation) instructions to build native modules.
