### ISSUE TITLE
Uncaught exception on app start on OS X

### ISSUE THREAD

**Issue by voronianski** [princejwesley/Mancy#83]
<img width="541" alt="2016-01-05 12 32 42" src="https://cloud.githubusercontent.com/assets/974035/12112989/a28d25bc-b3a8-11e5-808d-5a060fa1055f.png">

I'm on OS X 10.11.2 (15C50), node version is 0.12.7

**Comment by princejwesley** [comment]
@voronianski can you reproduce it in latest(`master` branch) code?

**Comment by voronianski** [comment]
@princejwesley I will check `master` branch a bit later.

**Comment by voronianski** [comment]
@princejwesley I've cloned the repo and tried to run `npm install` and `npm start` from `master` branch -

unfortunately there were errors while installing dependencies that I cannot resolve for now:

```bash
MacBook-Pro-Dmitri:Mancy dmitri$ npm install

> mancy@2.1.0 preinstall /Users/dmitri/github/Mancy
> npm prune

\
> font-manager@0.1.0 install /Users/dmitri/github/Mancy/node_modules/font-manager
> node-gyp rebuild

  CXX(target) Release/obj.target/fontmanager/src/FontManager.o
../src/FontManager.cc:92:18: error: no matching member function for call to 'Call'
  req->callback->Call(1, info);
  ~~~~~~~~~~~~~~~^~~~
../node_modules/nan/nan.h:1421:3: note: candidate function not viable: no known conversion from 'Handle<v8::Value> [1]' to 'v8::Local<v8::Value> *' for 2nd argument
  Call(int argc, v8::Local<v8::Value> argv[]) const {
  ^
../node_modules/nan/nan.h:1409:3: note: candidate function not viable: requires 3 arguments, but 2 were provided
  Call(v8::Local<v8::Object> target
  ^
../src/FontManager.cc:176:27: error: no matching member function for call to 'Set'
    info.GetReturnValue().Set(res);
    ~~~~~~~~~~~~~~~~~~~~~~^~~
../node_modules/nan/nan_callbacks_12_inl.h:46:15: note: candidate function not viable: no known conversion from 'Handle<v8::Value>' to 'bool' for 1st argument
  inline void Set(bool value) {
              ^
../node_modules/nan/nan_callbacks_12_inl.h:51:15: note: candidate function not viable: no known conversion from 'Handle<v8::Value>' to 'double' for 1st argument
  inline void Set(double i) {
              ^
../node_modules/nan/nan_callbacks_12_inl.h:56:15: note: candidate function not viable: no known conversion from 'Handle<v8::Value>' to 'int32_t' (aka 'int') for 1st argument
  inline void Set(int32_t i) {
              ^
../node_modules/nan/nan_callbacks_12_inl.h:61:15: note: candidate function not viable: no known conversion from 'Handle<v8::Value>' to 'uint32_t' (aka 'unsigned int') for 1st
      argument
  inline void Set(uint32_t i) {
              ^
../node_modules/nan/nan_callbacks_12_inl.h:27:37: note: candidate template ignored: could not match 'Local' against 'Handle'
  template <typename S> inline void Set(const v8::Local<S> &handle) {
                                    ^
../node_modules/nan/nan_callbacks_12_inl.h:32:37: note: candidate template ignored: could not match 'Global' against 'Handle'
  template <typename S> inline void Set(const Global<S> &handle) {
                                    ^
../node_modules/nan/nan_callbacks_12_inl.h:89:15: note: candidate template ignored: could not match 'S *' against 'Handle<v8::Value>'
  inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
              ^
../src/FontManager.cc:216:27: error: no matching member function for call to 'Set'
    info.GetReturnValue().Set(wrapResult(substituteFont(*postscriptName, *substitutionString)));
    ~~~~~~~~~~~~~~~~~~~~~~^~~
../node_modules/nan/nan_callbacks_12_inl.h:46:15: note: candidate function not viable: no known conversion from 'Handle<v8::Value>' to 'bool' for 1st argument
  inline void Set(bool value) {
              ^
../node_modules/nan/nan_callbacks_12_inl.h:51:15: note: candidate function not viable: no known conversion from 'Handle<v8::Value>' to 'double' for 1st argument
  inline void Set(double i) {
              ^
../node_modules/nan/nan_callbacks_12_inl.h:56:15: note: candidate function not viable: no known conversion from 'Handle<v8::Value>' to 'int32_t' (aka 'int') for 1st argument
  inline void Set(int32_t i) {
              ^
../node_modules/nan/nan_callbacks_12_inl.h:61:15: note: candidate function not viable: no known conversion from 'Handle<v8::Value>' to 'uint32_t' (aka 'unsigned int') for 1st
      argument
  inline void Set(uint32_t i) {
              ^
../node_modules/nan/nan_callbacks_12_inl.h:27:37: note: candidate template ignored: could not match 'Local' against 'Handle'
  template <typename S> inline void Set(const v8::Local<S> &handle) {
                                    ^
../node_modules/nan/nan_callbacks_12_inl.h:32:37: note: candidate template ignored: could not match 'Global' against 'Handle'
  template <typename S> inline void Set(const Global<S> &handle) {
                                    ^
../node_modules/nan/nan_callbacks_12_inl.h:89:15: note: candidate template ignored: could not match 'S *' against 'Handle<v8::Value>'
  inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
              ^
3 errors generated.
make: *** [Release/obj.target/fontmanager/src/FontManager.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dmitri/github/Mancy/node_modules/font-manager
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! font-manager@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the font-manager@0.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the font-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls font-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dmitri/github/Mancy/npm-debug.log
```

Maybe it's because of your fork of font-manager - `"font-manager": "https://github.com/princejwesley/font-manager.git"`

Also running `npm start` results in empty window - 

<img width="1087" alt="2016-01-06 13 23 41" src="https://cloud.githubusercontent.com/assets/974035/12141686/64a91b48-b47a-11e5-9e39-7230b1f401b2.png">

**Comment by princejwesley** [comment]
@voronianski Yes, My fork has support for 4.x, 5.x versions of node. Original author accepted my PR and tweaked to support 0.x node versions.

**Comment by princejwesley** [comment]
@voronianski Updated `package.json` to point to original `font-manager`.

**Comment by voronianski** [comment]
@princejwesley pulled your change and successfully built the app, however still the initial window is not open and when I click `New Window` -> have this exception:

```bash
Uncaught Exception:
TypeError: Buttons need to be array
    at Object.module.exports.showMessageBox (/Users/dmitri/github/Mancy/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:126:15)
    at aboutMancy (/Users/dmitri/github/Mancy/build/main/MancyApplication.js:205:24)
    at MenuItem.click (/Users/dmitri/github/Mancy/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/menu-item.js:69:20)
    at Function.delegate.executeCommand (/Users/dmitri/github/Mancy/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/menu.js:125:71)
```

**Comment by voronianski** [comment]
@princejwesley when I click `New Window` or `Preferences` nothing happens.

**Comment by voronianski** [comment]
@princejwesley some logs from console:

```bash
MacBook-Pro-Dmitri:Mancy dmitri$ npm start

> mancy@2.1.0 start /Users/dmitri/github/Mancy
> gulp start

[14:33:53] Requiring external module babel-core/register
[14:34:05] Using gulpfile ~/github/Mancy/gulpfile.babel.js
[14:34:05] Starting 'user-env'...
[14:34:05] Finished 'user-env' after 164 μs
[14:34:05] Starting 'start'...
[14:34:05] Starting 'rebuild'...
[14:34:05] Starting 'watchableCopy'...
[14:34:05] Finished 'watchableCopy' after 126 ms
[14:34:05] Starting 'sass'...
[14:34:06] Finished 'sass' after 692 ms
[14:34:06] Starting 'react'...
[14:34:13] Finished 'react' after 6.89 s
[14:34:13] Finished 'rebuild' after 7.71 s
[14:34:13] Starting 'run'...
[14:37:28] (node) warning: possible EventEmitter memory leak detected. 11 application:sync-preference listeners added. Use emitter.setMaxListeners() to increase limit.

[14:37:28] Trace
    at EventEmitter.addListener (events.js:239:17)
    at listenToSyncPreference (/Users/dmitri/github/Mancy/build/main/MancyApplication.js:213:27)
    at MancyApplication.rendererEvents (/Users/dmitri/github/Mancy/build/main/MancyApplication.js:257:7)
    at new MancyApplication (/Users/dmitri/github/Mancy/build/main/MancyApplication.js:70:11)
    at MenuManager.attachToWindow (/Users/dmitri/github/Mancy/build/main/MenuManager.js:72:31)
    at onReady (/Users/dmitri/github/Mancy/build/main/index.js:193:15)
    at EventEmitter.<anonymous> (/Users/dmitri/github/Mancy/build/main/index.js:77:5)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
(node) warning: possible EventEmitter memory leak detected. 11 application:check-new-release listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at listenToCheckNewRelease (/Users/dmitri/github/Mancy/build/main/MancyApplication.js:245:27)
    at MancyApplication.rendererEvents (/Users/dmitri/github/Mancy/build/main/MancyApplication.js:258:7)
    at new MancyApplication (/Users/dmitri/github/Mancy/build/main/MancyApplication.js:70:11)
    at MenuManager.attachToWindow (/Users/dmitri/github/Mancy/build/main/MenuManager.js:72:31)
    at onReady (/Users/dmitri/github/Mancy/build/main/index.js:193:15)
    at EventEmitter.<anonymous> (/Users/dmitri/github/Mancy/build/main/index.js:77:5)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

**Comment by princejwesley** [comment]
@voronianski Unfortunately I am not able reproduce this issue in my environment. let me try with ` 0.12.7` version.

**Comment by princejwesley** [comment]
@voronianski I am not able to reproduce this issue. I understand the problem. I'll fix it. 
Meantime, try this dirty fix 
src/main/index.js
```
require('events').EventEmitter.defaultMaxListeners = Infinity;
```
I wonder why `MancyApplication.rendererEvents` called more than 10 times. it suppose to be called per window.

**Comment by princejwesley** [comment]
@voronianski I wonder why both latest build and master branch code are not working for you.

Regarding `About Mancy` menu item,
> TypeError: Buttons need to be array

```js
  aboutMancy(item, focusedWindow) {
    let options = {
      title: 'About Mancy',
      buttons: ['Close'], // button array
      type: 'info',
      message: `${Config.description} (v${Config.version})`,
      detail: `${Config.license} Copyright (c) 2015 ${Config.author}`
    };

    dialog.showMessageBox(focusedWindow, options);
  }

```
`showMessageBox` source:
https://github.com/atom/electron/blob/master/atom/browser/api/lib/dialog.coffee#L92

**Comment by princejwesley** [comment]
Addressed `Buttons need to be array` issue  [:link:](https://github.com/atom/electron/pull/4057)
