### ISSUE TITLE
npm install fails with node-gyp error

### ISSUE THREAD

**Issue by siemiatj** [princejwesley/Mancy#85]
When I tried running `npm install` I got this :

```
> node-gyp rebuild

  CXX(target) Release/obj.target/fontmanager/src/FontManager.o

clang: error: no such file or directory: 'React/Mancy/node_modules/electron-rebuild/lib/headers/.node-gyp/0.36.3/include/node'
clang: error: no such file or directory: 'React/Mancy/node_modules/electron-rebuild/lib/headers/.node-gyp/0.36.3/src'
clang: error: no such file or directory: 'React/Mancy/node_modules/electron-rebuild/lib/headers/.node-gyp/0.36.3/deps/uv/include'
clang: error: no such file or directory: 'React/Mancy/node_modules/electron-rebuild/lib/headers/.node-gyp/0.36.3/deps/v8/include'
make: *** [Release/obj.target/fontmanager/src/FontManager.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/sasklacz/Work/Learning React/Mancy/node_modules/electron-rebuild/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/Users/sasklacz/.nvm/versions/node/v4.0.0/bin/node" "/Users/sasklacz/Work/Learning React/Mancy/node_modules/electron-rebuild/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sasklacz/Work/Learning React/Mancy/node_modules/font-manager
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/sasklacz/.nvm/versions/node/v4.0.0/bin/node" "/Users/sasklacz/Work/Learning React/Mancy/node_modules/electron-rebuild/node_modules/npm/bin/npm-cli.js" "rebuild" "--runtime=electron" "--target=0.36.3" "--arch=x64"
npm ERR! node v4.0.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! font-manager@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the font-manager@0.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the font-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs font-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls font-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sasklacz/Work/Learning React/Mancy/node_modules/npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/Users/sasklacz/Work/Learning React/Mancy/node_modules/electron-rebuild/lib/spawn.js:55:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/sasklacz/.nvm/versions/node/v4.0.0/bin/node" "/Users/sasklacz/.nvm/versions/node/v4.0.0/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! mancy@2.2.0 postinstall: `electron-rebuild && gulp clean && gulp copy`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the mancy@2.2.0 postinstall script 'electron-rebuild && gulp clean && gulp copy'.
npm ERR! This is most likely a problem with the mancy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild && gulp clean && gulp copy
npm ERR! You can get their info via:
npm ERR!     npm owner ls mancy
npm ERR! There is likely additional logging output above.
```

aaand it crashes. I tried rebuilding the fonts npm module manually with `node-gyp` but it didn't help.

```
[Work] node --version
v4.0.0
[Work] npm --version
2.14.2
```

**Comment by antonyr** [comment]
@siemiatj It seems your current working directory is `/Users/sasklacz/Work/Learning React/Mancy` and this path has space between `Learning` and `React`

Could you please retry compiling once again by removing space or replacing space with underscore?

**Comment by siemiatj** [comment]
Yup, this fixed it. Thanks !
