### ISSUE TITLE
install failure on Ubuntu

### ISSUE THREAD

**Issue by igalic** [princejwesley/Mancy#90]
```
igalic@levix ~/s/p/Mancy (master|✔)> npm install
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN prefer global npm@3.5.3 should be installed with -g
npm WARN prefer global cover@0.2.9 should be installed with -g
npm WARN prefer global node-gyp@3.2.1 should be installed with -g

> nslog@3.0.0 install /home/igalic/src/plt/Mancy/node_modules/nslog
> node-gyp rebuild



igalic@levix ~/s/p/Mancy (master|✔) [1]> npm run package

> mancy@2.2.0 package /home/igalic/src/plt/Mancy
> gulp package

[10:36:29] Requiring external module babel-core/register
[10:36:33] Using gulpfile ~/src/plt/Mancy/gulpfile.babel.js
[10:36:33] Starting 'build'...
[10:36:33] Starting 'clean'...
[10:36:33] Finished 'clean' after 8.96 ms
[10:36:33] Starting 'watchableCopy'...
[10:36:34] Finished 'watchableCopy' after 88 ms
[10:36:34] Starting 'copy'...
[10:36:54] Finished 'copy' after 20 s
[10:36:54] Starting 'sass'...
[10:36:54] 'sass' errored after 31 ms
[10:36:54] Error: The `libsass` binding was not found in /home/igalic/src/plt/Mancy/node_modules/node-sass/vendor/linux-x64-47/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/home/igalic/src/plt/Mancy/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/home/igalic/src/plt/Mancy/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:397:26)
    at Module._extensions..js (module.js:404:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/igalic/src/plt/Mancy/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/igalic/src/plt/Mancy/node_modules/gulp-sass/index.js:183:21)
[10:36:54] 'build' errored after 20 s
[10:36:54] Error in plugin 'run-sequence'
Message:
    An error occured in task 'sass'.

npm ERR! Linux 4.2.0-23-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "package"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! mancy@2.2.0 package: `gulp package`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mancy@2.2.0 package script 'gulp package'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mancy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp package
npm ERR! You can get their info via:
npm ERR!     npm owner ls mancy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/igalic/src/plt/Mancy/npm-debug.log
igalic@levix ~/s/p/Mancy (master|✔) [1]>
```

here's the npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'package' ]
2 info using npm@3.3.12
3 info using node@v5.4.1
4 verbose run-script [ 'prepackage', 'package', 'postpackage' ]
5 info lifecycle mancy@2.2.0~prepackage: mancy@2.2.0
6 silly lifecycle mancy@2.2.0~prepackage: no script for prepackage, continuing
7 info lifecycle mancy@2.2.0~package: mancy@2.2.0
8 verbose lifecycle mancy@2.2.0~package: unsafe-perm in lifecycle true
9 verbose lifecycle mancy@2.2.0~package: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/igalic/src/plt/Mancy/node_modules/.bin:/opt/rumprun/bin:/home/igalic/bin:/opt/puppetlabs/bin:/opt/puppetlabs/puppet/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle mancy@2.2.0~package: CWD: /home/igalic/src/plt/Mancy
11 silly lifecycle mancy@2.2.0~package: Args: [ '-c', 'gulp package' ]
12 silly lifecycle mancy@2.2.0~package: Returned: code: 1  signal: null
13 info lifecycle mancy@2.2.0~package: Failed to exec package script
14 verbose stack Error: mancy@2.2.0 package: `gulp package`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid mancy@2.2.0
16 verbose cwd /home/igalic/src/plt/Mancy
17 error Linux 4.2.0-23-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "package"
19 error node v5.4.1
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error mancy@2.2.0 package: `gulp package`
22 error Exit status 1
23 error Failed at the mancy@2.2.0 package script 'gulp package'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mancy package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp package
23 error You can get their info via:
23 error     npm owner ls mancy
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by princejwesley** [comment]
@igalic run  `npm rebuild node-sass` and then `npm install` which will run `electron-rebuild` as part of `postinstall` script. Finally generate package using `npm run package`

**Comment by igalic** [comment]
\o/ thanks
