### ISSUE TITLE
Object.keys causes SyntaxError

### ISSUE THREAD

**Issue by BrandonSmith** [princejwesley/Mancy#91]
Entering the following results in a Syntax Error claiming Unexpected token import.

```
Object.keys({a:'b'})
```

```
import _Object$keys from 'babel-runtime/core-js/object/keys';_Object$keys({ a: 'b' });
SyntaxError:  Unexpected token import
  at Object._vm2.default.createScript (/Applications/Mancy.app/Contents/Resources/app/common/ReplContext.js:123:8)
  at Object.runInContext (/Applications/Mancy.app/Contents/Resources/app/common/ReplCommon.js:357:33)
  at ReplActiveInput.transpileAndExecute (/Applications/Mancy.app/Contents/Resources/app/components/ReplActiveInput.js:555:30)
  at /Applications/Mancy.app/Contents/Resources/app/components/ReplActiveInput.j(s:611:20)
```

**Comment by princejwesley** [comment]
@BrandonSmith Sorry about that. if you have `Babel Transform` turned on, turn on `strict` REPL mode. In this case, babel imports polyfills and `import` has to be used with `strict` mode.

**Comment by princejwesley** [comment]
@BrandonSmith [transformed](https://github.com/princejwesley/Mancy/commit/da59b21a0a0dd9536972944c08063f00676c8620) `import` to `require` statements to avoid issues like this.

**Comment by princejwesley** [comment]
Fix is available in master branch
